### ISSUE TITLE
Running in float32 or float64

### ISSUE THREAD

**Issue by Sean-Reilly** [MilesCranmer/PySR#41] opened 2021-04-01 03:47 UTC
Hi Miles,

Is there a way for this to run in `float64` or `float32` at run time, rather than modding the code?  I am writing some code that uses PySR, and the changes we made to make it work previously will likely not apply cleanly if we pull the changes to PySR up, in it's current state.  If not, do you have any advice on making this work?

**Comment by MilesCranmer** [comment] 2021-04-01 05:04
Hi,

Good question. For now, no, but I will add this change to PySR later this week. The backend fully supports it, just haven't enabled it in PySR yet.

The mod to the code right now is to replace float32 with float64 and Float32 with Float64 in these lines: https://github.com/MilesCranmer/PySR/blob/2309acf16b025b50b423514d2e6557c0ca1bbca9/pysr/sr.py#L445-L454

Cheers,
Miles

**Comment by Sean-Reilly** [comment] 2021-04-05 20:51
Thank you Much for your quick Response!

**Comment by Sean-Reilly** [comment] 2021-06-18 19:56
Hello Miles,

Wanted to check in on this issue since we're still having some trouble with it.  To begin I've tried making extensive changes, including the one you mentioned, to get the precision to be where I want it to be.  It was quite a bit more extensive change than just changing that section you mentioned, with there being many instances of `Float32` in the Julia backend as well, and have been trying to enable selecting `Float32` or `Float64` in the code at runtime rather than having to find all the instances and change them manually.  

To this end I've hit a wall, with the dependency the way it is I'm having trouble calling in the selected precision into `ProgramConstants.jl`, since the `precision` variable is set through the `hyperparams.jl` which are generated by `sr.py`.  Originally I had it just adjust the values in `Options.jl`, which works fine, but isn't achieving the true `Float64` precision without changing every instance of `Float32` in both `Equation.jl` and `ProgramConstants.jl`, and I can't bring in the `precision` variable into those files because of the dependency tree.  

My goal is to enable the selection of floating point precision as a parameter of `sr.py` that can be set when running the code, so that you can maintain the precision others need while also allowing for higher precision calculations, eventually to be included hopefully as a pull for the repo.  Do you have any further insight into this?  Are there any changes you would be willing to make to make this easier?

**Comment by MilesCranmer** [comment] 2021-06-19 18:35
Hey,
sorry for forgetting to do this. I'm working on it now before I forget again. Just pushed to `master` branch.

The constants in each equation are hardcoded to 32-bit precision. Just so I understand, why do you need 64-bit precision in the constants? I wouldn't expect it to actually reach that level of precision in optimizing them (since it simultaneously is searching over equations, it's hard to optimize both); even Float32 is probably too much for the constants and Float16 might be good enough. To reach 64-bit level of precision, I would probably do post-processing and re-optimize the constants in the equation with a normal optimizer. (both `export_torch_format` and `export_jax_format` give you a representation with tunable parameters).

Cheers,
Miles

**Comment by Sean-Reilly** [comment] 2021-06-22 20:48
Hi again,

Thank you so much for updating to support this, if I have any other issues/concerns regarding this I'll post them here.  To answer your question, I'm trying to reproduce a theoretical model for a mathematical representation of molecular dynamics, so it has to be incredibly high precision to pass the MSE 'bar' we're looking for.  I'll pass along your suggestions to my PI and we'll see how feasible that is for the project.  

Thanks again!

**Comment by MilesCranmer** [comment] 2021-06-23 15:11
Awesome! Sounds like a really interesting project. 
Another thing you might consider trying is: after learning an equation to approximately fit your system, if it’s not enough precision, then learn the remaining error with a much more flexible model like a NNet. That way, the majority of your model is analytic, but it gets to a high level of precision using a NNet to pick up the slack.

**Comment by MilesCranmer** [comment] 2022-05-20 15:05
Closed with the `precision` argument in PySR, although constants are still fixed in Float32. I think arbitrary complexity could be added for the constants fairly easily, but that is not yet done. If needed, one can change `CONST_TYPE` in the SymbolicRegression.jl source code, and specify the custom source with `julia_project` in pysr.

**Closed by MilesCranmer** 2022-05-20 15:05 UTC
Labels: enhancement, implemented

**Comment by MilesCranmer** [comment] 2022-08-30 17:57
Hi @Sean-Reilly,
If you're still interested in this, I have a draft PR here: https://github.com/MilesCranmer/SymbolicRegression.jl/pull/119 which adds support for arbitrary types of constants in the expressions.
Cheers,
Miles
