### ISSUE TITLE
[BUG] *not working if y is pd.DataFrame*

### ISSUE THREAD

**Issue by butter517cup** [MilesCranmer/PySR#122] opened 2022-04-06 20:42 UTC
It works when ` X` is `pd.DataFrame`.
However, if `y` is `pd.DataFrame`, it gives the following error (it works if `y` is `np.array` though):

Warning (from warnings module):
  File "C:\Program Files\Python39\lib\site-packages\pysr\sr.py", line 942
    warnings.warn("Resetting variable_names from X.columns")
UserWarning: Resetting variable_names from X.columns
Traceback (most recent call last):
  File "C:\Users\butter\Documents\pySR_test.py", line 41, in <module>
    model.fit(X, y)
  File "C:\Program Files\Python39\lib\site-packages\pysr\sr.py", line 808, in fit
    self._run(
  File "C:\Program Files\Python39\lib\site-packages\pysr\sr.py", line 953, in _run
    assert not isinstance(y, pd.DataFrame)
AssertionError

If `y` is `pd.Series` it gives following error:
Traceback (most recent call last):
  File "C:\Users\butter\Documents\pySR_test.py", line 41, in <module>
    model.fit(X, y)
  File "C:\Program Files\Python39\lib\site-packages\pysr\sr.py", line 808, in fit
    self._run(
  File "C:\Program Files\Python39\lib\site-packages\pysr\sr.py", line 985, in _run
    y = y.reshape(-1)
  File "C:\Program Files\Python39\lib\site-packages\pandas\core\generic.py", line 5583, in __getattr__
    return object.__getattribute__(self, name)
AttributeError: 'Series' object has no attribute 'reshape'

I think it would be fine to work with `y` too DataFrame.

**Comment by MilesCranmer** [comment] 2022-04-09 17:06
This is actually expected behaviour - hence why there's the AssertionError. However, you raise a good point and I think I should just automatically convert `pd.Series` into numpy arrays internally, since to the user it seems like if `X` can be a series, then `y` should be too. Will close this when it's added.

**Comment by MilesCranmer** [comment] 2022-04-26 20:41
Fixed with [ad8332d](https://github.com/MilesCranmer/PySR/commit/ad8332d016b1b3310306f6b2c7ef8166ff9e5de1). y can be a pd.Series or pd.DataFrame.

**Closed by MilesCranmer** 2022-04-26 20:41 UTC
Labels: bug
